name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  statuses: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install `just` from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
      - run: just check-ci
